[context.production.environment]
HUGO_VERSION = "0.62.2-83E50184/extended"
HUGO_ENV = "production"
RUBY_VERSION = "2.6.2"

[context.deploy-preview.environment]
HUGO_VERSION = "0.62.2-83E50184/extended"
RUBY_VERSION = "2.6.2"
